apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cdn
  namespace: personal-cinema
spec:
  serviceName: "postgres-cdn"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cdn
  template:
    metadata:
      labels:
        app: postgres-cdn
    spec:
      containers:
        - name: postgres-cdn
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: cdn-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cdn-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cdn-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
