version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:5173"
    volumes:
      - .:/var/www
    networks:
      - frontend
    working_dir: /var/www
    command: npm run dev -- --host 0.0.0.0

networks:
  frontend:
    driver: bridge
