# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    #esi: true
    #fragments: true

    http_method_override: true
    handle_all_throwables: true
    php_errors:
        log: true
    session:
        cookie_secure: auto
        cookie_samesite: lax
        handler_id: session.handler.native_file

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file