nelmio_api_doc:
    documentation:
        info:
            title: Personal cinema
            description: A web application for sharing personal audio-visual files.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                FolderQueryRequest:
                    title: FolderQueryRequest
                    description: Nějaký test
    areas:
        path_patterns:
            - ^/v1(?!/doc$) # Accepts routes under /v1 except /v1/doc