version: '3.8'

services:
  php-fpm:
    image: furstd/personal-cinema_backend:latest
    networks:
      - backend
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend_php.rule=Host(`api.soukromekino.cz`)"
      - "traefik.http.routers.backend_php.entrypoints=websecure"
      - "traefik.http.routers.backend_php.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend_php.loadbalancer.server.port=9000"
      - "traefik.docker.network=backend"

  nginx:
    image: furstd/personal-cinema_nginx:latest
    ports:
      - "8080:80"
    networks:
      - backend
    depends_on:
      - php-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend_nginx.rule=Host(`api.soukromekino.cz`)"
      - "traefik.http.routers.backend_nginx.entrypoints=websecure"
      - "traefik.http.routers.backend_nginx.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend_nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=backend"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db_data:
