services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./symfony:/var/www
    working_dir: /var/www
    networks:
      - backend
    command: sh -c "chown -R appuser:appuser /var/www/var/log && chmod -R 775 /var/www/var/log && composer install && php-fpm"
    env_file:
      - ./.env

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
      - ./symfony:/var/www
    networks:
      - backend
    depends_on:
      - php-fpm

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
