apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  POSTGRES_DB: {{ .Values.backend.secret.POSTGRES_DB | b64enc }}
  POSTGRES_USER: {{ .Values.backend.secret.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.backend.secret.POSTGRES_PASSWORD | b64enc }}
