services:
  frontend-admin:
    build: .
    ports:
      - "3001:5174"
    volumes:
      - .:/var/www
    networks:
      - frontend-admin
    working_dir: /var/www
    command: npm run dev -- --host 0.0.0.0

networks:
  frontend-admin:
    driver: bridge
