version: '3.8'

services:
  traefik:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=dominikfurst1@seznam.cz"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--providers.docker.network=frontend-admin"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./acme.json:/acme.json"
    networks:
      - backend
      - frontend
      - frontend-admin

networks:
  backend:
    external:
      name: backend
  frontend:
    external:
      name: frontend
  frontend-admin:
    external:
      name: frontend-admin
