services:
  cdn-api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - minio
      - redis
      - postgres-cdn
    volumes:
      - .:/var/www
    command: npm run dev
    networks:
      - cdn-backend

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - cdn-backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - cdn-backend

  postgres-cdn:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cdn-backend

networks:
  cdn-backend:
    driver: bridge

volumes:
  minio_data:
  postgres_data:
