# Use the official Node.js image as a parent image
FROM node:20-alpine

# Set the working directory to /var/www
WORKDIR /var/www

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 4000

# Start the app
CMD ["node", "src/index.js"]
