services:
  cdn-api:
    image: furstd/personal-cinema_backend_cdn:latest
    env_file:
      - .env
    depends_on:
      - minio
      - redis
      - postgres-cdn
    networks:
      - cdn-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdn-api.rule=Host(`api.cdn.soukromekino.cz`)"
      - "traefik.http.routers.cdn-api.entrypoints=websecure"
      - "traefik.http.routers.cdn-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.cdn-api.loadbalancer.server.port=4000"
      - "traefik.docker.network=cdn-backend"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: https://file.soukromekino.cz/
    volumes:
      - minio_data:/data
    networks:
      - cdn-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`file.soukromekino.cz`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

      - "traefik.http.routers.minio-console.rule=Host(`admin.file.soukromekino.cz`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.docker.network=cdn-backend"

  redis:
    image: redis
    networks:
      - cdn-backend
    deploy:
      resources:
        limits:
          memory: 512M

  postgres-cdn:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cdn-backend

networks:
  cdn-backend:
    name: cdn-backend
    driver: bridge

volumes:
  minio_data:
  postgres_data:
