<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240819084350 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quality INT NOT NULL, video_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BD91274429C1004E ON conversion (video_id)');
        $this->addSql('ALTER TABLE conversion ADD CONSTRAINT FK_BD91274429C1004E FOREIGN KEY (video_id) REFERENCES video (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video DROP path');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE conversion DROP CONSTRAINT FK_BD91274429C1004E');
        $this->addSql('DROP TABLE conversion');
        $this->addSql('ALTER TABLE video ADD path VARCHAR(255) DEFAULT NULL');
    }
}
