<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240814092615 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE storage_card_payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id VARCHAR(255) NOT NULL, storage_upgrade_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_76518EDC613FECDF ON storage_card_payment (session_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_76518EDC8259D30 ON storage_card_payment (storage_upgrade_id)');
        $this->addSql('CREATE TABLE storage_upgrade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price_czk INT NOT NULL, size BIGINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C05A47789B6B5FBA ON storage_upgrade (account_id)');
        $this->addSql('ALTER TABLE storage_card_payment ADD CONSTRAINT FK_76518EDC8259D30 FOREIGN KEY (storage_upgrade_id) REFERENCES storage_upgrade (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE storage_upgrade ADD CONSTRAINT FK_C05A47789B6B5FBA FOREIGN KEY (account_id) REFERENCES "account" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE storage_card_payment DROP CONSTRAINT FK_76518EDC8259D30');
        $this->addSql('ALTER TABLE storage_upgrade DROP CONSTRAINT FK_C05A47789B6B5FBA');
        $this->addSql('DROP TABLE storage_card_payment');
        $this->addSql('DROP TABLE storage_upgrade');
    }
}
