<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240819112218 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, width INT NOT NULL, height INT NOT NULL, bandwidth INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE video_conversion (video_id INT NOT NULL, conversion_id INT NOT NULL, PRIMARY KEY(video_id, conversion_id))');
        $this->addSql('CREATE INDEX IDX_3D363FF229C1004E ON video_conversion (video_id)');
        $this->addSql('CREATE INDEX IDX_3D363FF24C1FF126 ON video_conversion (conversion_id)');
        $this->addSql('ALTER TABLE video_conversion ADD CONSTRAINT FK_3D363FF229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_conversion ADD CONSTRAINT FK_3D363FF24C1FF126 FOREIGN KEY (conversion_id) REFERENCES conversion (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video DROP path');
        $this->addSql('INSERT INTO conversion (width, height, bandwidth) VALUES (256, 144, 80000)');
        $this->addSql('INSERT INTO conversion (width, height, bandwidth) VALUES (426, 240, 200000)');
        $this->addSql('INSERT INTO conversion (width, height, bandwidth) VALUES (640, 360, 400000)');
        $this->addSql('INSERT INTO conversion (width, height, bandwidth) VALUES (854, 480, 800000)');
        $this->addSql('INSERT INTO conversion (width, height, bandwidth) VALUES (1280, 720, 1500000)');
        $this->addSql('INSERT INTO conversion (width, height, bandwidth) VALUES (1920, 1080, 3000000)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE video_conversion DROP CONSTRAINT FK_3D363FF229C1004E');
        $this->addSql('ALTER TABLE video_conversion DROP CONSTRAINT FK_3D363FF24C1FF126');
        $this->addSql('DROP TABLE conversion');
        $this->addSql('DROP TABLE video_conversion');
        $this->addSql('ALTER TABLE video ADD path VARCHAR(255) DEFAULT NULL');
    }
}
