<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240813081313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE storage_upgrade_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, size BIGINT NOT NULL, price_czk INT NOT NULL, percentage_discount INT NOT NULL, discount_expiration_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('INSERT INTO storage_upgrade_price (id, size, price_czk, percentage_discount, discount_expiration_at) VALUES (1, 10737418240, 69, 0, NULL)');
        $this->addSql('INSERT INTO storage_upgrade_price (id, size, price_czk, percentage_discount, discount_expiration_at) VALUES (2, 21474836480, 119, 0, NULL)');
        $this->addSql('INSERT INTO storage_upgrade_price (id, size, price_czk, percentage_discount, discount_expiration_at) VALUES (3, 42949672960, 219, 0, NULL)');
        $this->addSql('INSERT INTO storage_upgrade_price (id, size, price_czk, percentage_discount, discount_expiration_at) VALUES (4, 75161927680, 369, 0, NULL)');
        $this->addSql('INSERT INTO storage_upgrade_price (id, size, price_czk, percentage_discount, discount_expiration_at) VALUES (5, 107374182400, 499, 0, NULL)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE storage_upgrade_price');
    }
}
