<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240715125848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE account ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN account.created_at IS \'\'');
        $this->addSql('ALTER TABLE api_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE api_token ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE api_token ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN api_token.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN api_token.updated_at IS \'\'');
        $this->addSql('ALTER TABLE folder ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE folder ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE folder ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN folder.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN folder.updated_at IS \'\'');
        $this->addSql('ALTER TABLE md5 ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE role ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE settings ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX uniq_7cc7da2cdbea601a');
        $this->addSql('ALTER TABLE video DROP cdn_link');
        $this->addSql('ALTER TABLE video ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE video ALTER cdn_id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE video ALTER cdn_id TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE video ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE video ALTER deleted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN video.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN video.deleted_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE folder ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE folder ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE folder ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN folder.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN folder.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE api_token ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE api_token ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE api_token ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN api_token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN api_token.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE role ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE md5 ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "account" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "account" ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN "account".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE settings ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE video ADD cdn_link VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE video ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE video ALTER cdn_id TYPE INT');
        $this->addSql('ALTER TABLE video ALTER cdn_id TYPE INT');
        $this->addSql('ALTER TABLE video ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE video ALTER deleted_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN video.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN video.deleted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_7cc7da2cdbea601a ON video (cdn_link)');
    }
}
