apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-minio
  ports:
    - protocol: TCP
      port: {{ index .Values.cdnBackend.minio.ports 0 }}
      targetPort: {{ index .Values.cdnBackend.minio.ports 0 }}
      name: api
    - protocol: TCP
      port: {{ index .Values.cdnBackend.minio.ports 1 }}
      targetPort: {{ index .Values.cdnBackend.minio.ports 1 }}
      name: console
