apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.cdnBackend.redis.port }}
      targetPort: {{ .Values.cdnBackend.redis.port }}
