apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cdn-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.cdnBackend.secret.POSTGRES_DB | b64enc | quote }}
  POSTGRES_USER: {{ .Values.cdnBackend.secret.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.cdnBackend.secret.POSTGRES_PASSWORD | b64enc | quote }}
  MINIO_ROOT_USER: {{ .Values.cdnBackend.secret.MINIO_ROOT_USER | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.cdnBackend.secret.MINIO_ROOT_PASSWORD | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.cdnBackend.secret.REDIS_PASSWORD | b64enc | quote }}
