apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: personal-cinema
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: furstd/personal-cinema_frontend_admin:latest
          ports:
            - containerPort: 4174
