name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Prepare Environment"]
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_PREFIX: "furstd/personal-cinema"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker images
        run: |
          docker build ./backend -t ${{ env.DOCKER_IMAGE_PREFIX }}_backend:latest 
          docker push ${{ env.DOCKER_IMAGE_PREFIX }}_backend:latest
          docker build -f ./backend/nginx/Dockerfile -t ${{ env.DOCKER_IMAGE_PREFIX }}_nginx:latest ./backend
          docker push ${{ env.DOCKER_IMAGE_PREFIX }}_nginx:latest

      - name: Build and push frontend Docker images
        run: |
          docker build -f ./frontend/Dockerfile.prod -t ${{ env.DOCKER_IMAGE_PREFIX }}_frontend:latest ./frontend
          docker push ${{ env.DOCKER_IMAGE_PREFIX }}_frontend:latest

      - name: Build and push admin frontend Docker images
        run: |
          docker build -f ./admin-frontend/Dockerfile.prod -t ${{ env.DOCKER_IMAGE_PREFIX }}_frontend_admin:latest ./admin-frontend
          docker push ${{ env.DOCKER_IMAGE_PREFIX }}_frontend_admin:latest

      - name: Build and push CDN backend Docker images
        run: |
          docker build -f ./cdn-backend/Dockerfile.prod -t ${{ env.DOCKER_IMAGE_PREFIX }}_backend_cdn:latest ./cdn-backend
          docker push ${{ env.DOCKER_IMAGE_PREFIX }}_backend_cdn:latest
