name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace environment variables in .env file
        run: |
          cp backend/.env.example backend/.env
          cp backend/symfony/.env.example backend/symfony/.env
          echo "Before substitution:"
          cat backend/.env
          cat backend/symfony/.env
          sed -i 's/db_name/${{ secrets.POSTGRES_DB }}/' backend/.env
          sed -i 's/db_user/${{ secrets.POSTGRES_USER }}/' backend/.env
          sed -i 's/db_password/${{ secrets.POSTGRES_PASSWORD }}/' backend/.env
          sed -i 's/app_secret/${{ secrets.APP_SECRET }}/' backend/symfony/.env
          sed -i 's/jwt_passphrase/${{ secrets.JWT_PASSPHRASE }}/' backend/symfony/.env
          echo "After substitution:"
          cat backend/.env
          cat backend/symfony/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build ./backend -t furstd/personal-cinema_backend:latest 
          docker push furstd/personal-cinema_backend:latest

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan $VPS_HOST >> ~/.ssh/known_hosts
          scp -i private_key backend/docker-compose.yml backend/docker-compose.prod.yml backend/.env backend/symfony/.env $VPS_USER@$VPS_HOST:/opt/soukromekino/backend/
          ssh -i private_key -T $VPS_USER@$VPS_HOST << 'EOF'
            cd /opt/soukromekino/backend/
            echo "Environment variables before starting Docker:"
            cat .env
            cat symfony/.env
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.prod.yml up -d
            docker-compose exec -T php-fpm php bin/console cache:clear
          EOF
