name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: '/opt/soukromekino'
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create necessary directories on VPS
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan $VPS_HOST >> ~/.ssh/known_hosts
          ssh -i private_key -T $VPS_USER@$VPS_HOST 'mkdir -p ${{ env.PROJECT_PATH }}/backend/symfony ${{ env.PROJECT_PATH }}/frontend ${{ env.PROJECT_PATH }}/admin-frontend ${{ env.PROJECT_PATH }}/cdn-backend'

      - name: Copy files to VPS
        run: |
          scp -i private_key backend/docker-compose.prod.yml $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/backend/
          scp -i private_key frontend/docker-compose.prod.yml $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/frontend/
          scp -i private_key admin-frontend/docker-compose.prod.yml $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/admin-frontend/
          scp -i private_key cdn-backend/docker-compose.prod.yml $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/cdn-backend/
          scp -i private_key traefik/docker-compose.yml $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/traefik/
          scp -i private_key traefik/traefik.toml $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/traefik/
          scp -i private_key backend/.env $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/backend/.env
          scp -i private_key backend/symfony/.env $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/backend/symfony/.env
          scp -i private_key frontend/.env $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/frontend/.env
          scp -i private_key admin-frontend/.env $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/admin-frontend/.env
          scp -i private_key cdn-backend/.env $VPS_USER@$VPS_HOST:${{ env.PROJECT_PATH }}/cdn-backend/

      - name: Pull services
        run: |
          ssh -i private_key -T $VPS_USER@$VPS_HOST 'docker-compose -f ${{ env.PROJECT_PATH }}/backend/docker-compose.prod.yml pull'
          ssh -i private_key -T $VPS_USER@$VPS_HOST 'docker-compose -f ${{ env.PROJECT_PATH }}/frontend/docker-compose.prod.yml pull'
          ssh -i private_key -T $VPS_USER@$VPS_HOST 'docker-compose -f ${{ env.PROJECT_PATH }}/admin-frontend/docker-compose.prod.yml pull'
          ssh -i private_key -T $VPS_USER@$VPS_HOST 'docker-compose -f ${{ env.PROJECT_PATH }}/cdn-backend/docker-compose.prod.yml pull'

      - name: Restart services
        run: |
          ssh -i private_key -T $VPS_USER@$
