name: Prepare Environment

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: '/opt/soukromekino'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace environment variables in .env file
        run: |
          cp backend/.env.example backend/.env
          cp backend/symfony/.env.example backend/symfony/.env
          cp frontend/.env.example frontend/.env
          cp admin-frontend/.env.example admin-frontend/.env
          cp cdn-backend/.env.example cdn-backend/.env
          sed -i 's|db_name|${{ secrets.POSTGRES_DB }}|' backend/.env
          sed -i 's|db_user|${{ secrets.POSTGRES_USER }}|' backend/.env
          sed -i 's|db_password|${{ secrets.POSTGRES_PASSWORD }}|' backend/.env
          sed -i 's|app_secret|${{ secrets.APP_SECRET }}|' backend/symfony/.env
          sed -i 's|jwt_passphrase|${{ secrets.JWT_PASSPHRASE }}|' backend/symfony/.env
          sed -i 's|sendgrid_api_key|${{ secrets.SENDGRID_API_KEY }}|' backend/symfony/.env
          sed -i 's|api_url|${{ secrets.API_URL }}|' frontend/.env
          sed -i 's|api_url|${{ secrets.API_URL }}|' admin-frontend/.env
          sed -i 's|db_name|${{ secrets.POSTGRES_CDN_DB }}|' cdn-backend/.env
          sed -i 's|db_user|${{ secrets.POSTGRES_CDN_USER }}|' cdn-backend/.env
          sed -i 's|db_password|${{ secrets.POSTGRES_CDN_PASSWORD }}|' cdn-backend/.env
          sed -i 's|minio_access_key|${{ secrets.MINIO_ACCESS_KEY }}|' cdn-backend/.env
          sed -i 's|minio_secret_key|${{ secrets.MINIO_SECRET_KEY }}|' cdn-backend/.env

      - name: Create JWT key files
        run: |
          mkdir -p backend/symfony/config/jwt
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > backend/symfony/config/jwt/private.pem
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > backend/symfony/config/jwt/public.pem
